version: '3'

services:
  redis1:
    image: redis:latest
    command: redis-server --port 6379
    ports:
      - 6379:6379

  redis2:
    image: redis:latest
    command: redis-server --port 6378
    ports:
      - 6378:6378

  distributed-joins:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis1
      - redis2
    ports:
      - 8080:8080 