version: '3'

services:
  redis1:
    image: redis:latest
    command: redis-server --port 6379
    ports:
      - 6379:6379

  redis2:
    image: redis:latest
    command: redis-server --port 6378
    ports:
      - 6378:6378

  distributed-joins:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis1
      - redis2
    environment:
      - FIRST_DATA_SIZE=10000
      - SECOND_DATA_SIZE=12000
      - PROBABILITY=0.1
      - DESIRED_RANGE=3
